services:
  ubuntu:
    container_name: ubuntu
    tty: true
    build:
      context: .
      dockerfile: ubuntu/Dockerfile
    volumes:
      - ../app:/app:rw
  
  emsdk:
    container_name: emsdk
    tty: true
    build:
      context: .
      dockerfile: emsdk/Dockerfile
    volumes:
      - ../app:/app:rw
